### PR TITLE
Prevent duplicate tour, and don't show the "standard" welcome tour for Free Tier

### LINKED ISSUE #5240: Onboarding Tour Displays Twice
### Current Behavior

https://github.com/user-attachments/assets/c600b8c1-c652-49bc-90f0-f59e26e275a8

The Free Tier onboarding tour correctly displays and supports me in creating my first Remote Instance, after that though, going to the "Applications" page, I then see another new tour, which actually triggers twice?

### Expected Behavior

I should not see any further tours, after creating my first Remote Instance

### Steps To Reproduce

- Create new user on "Free Tier"
- Add your Remote Instance as part of the tour
- Navigate to the "/applications" view

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- Singleton pattern to ensure we only have a single tour showing at once
- Removes the generic "Welcome" tour for Free Tier (FYI @gstout52) - it just felt too annoying, and the user would have already navigated through the Free Tier tour and added their first Remote Instance at that point. Having another new tour of "Welcome to FlowFuse" felt too much.

## Related Issue(s)

Closes #5240

### CODE REVIEW

File: frontend/src/pages/team/Applications/index.vue [hunk 1]
```diff
@@ -132,7 +132,8 @@ export default {
             columns: [
                 { label: 'Name', class: ['flex-grow'], key: 'name', sortable: true }
             ],
-            filterTerm: ''
+            filterTerm: '',
+            tour: null
```
Comment (cstns) [inline frontend/src/pages/team/Applications/index.vue:136]: love the singletone approach, two questions pop into my head:
1. should we clear the tour after it's completion?
2. should the tour be in the store for a more global approach?

thinking as I write, we can move it whenever we'd need something more widespread/global

Comment (joepavitt) [reply frontend/src/pages/team/Applications/index.vue:136]: > thinking as I write, we can move it whenever we'd need something more widespread/global

This, it's fine for now, when we have the need, then we build it

**Review by cstns — APPROVED** [review]
