### PR TITLE
Only get tokens if team feature enabled

### LINKED ISSUE #4382: Instance Settings page requesting httpToken list when not enabled for team
The Instance Settings Security page will show a list of HTTP Access Tokens if the FF User Auth option is enabled.

That option is gated on both the platform feature flag and the team type feature flag.

However the request to load the instance tokens is only gated by the platform feature flag.

So when a Starter team accesses that page, even though the option is disabled, we're still making a request to load the tokens under the covers. This correctly returns a 404 which throws an unhandled error under the covers.

There is no impact to the user, but this unhandled error is being reported by Sentry.

The request to get tokens (line 161 `frontend/src/pages/instance/Settings/Security.vue`) needs to check the team type feature flag as well as the platform flag.

Sentry Issue: [FLOWFUSE-FRONTEND-59](https://flowfuse.sentry.io/issues/5715437731/?referrer=github_integration)

```
AxiosError: Request failed with status code 404
  at Lt (/app/vendors.f3f35300cdfa825dec32.js:2:744787)
  at XMLHttpRequest.g (/app/vendors.f3f35300cdfa825dec32.js:2:749434)
  at pe.request (/app/vendors.f3f35300cdfa825dec32.js:2:757319)
  at async Proxy.getTokens (/app/main.43b5a997bb88bec17808.js:1:1020348)
```

### PR DESCRIPTION
**Pull request by hardillb**
fixes #4382

## Description

Prevents the UI from trying to access Bearer tokens if the FlowFuse User Authentication is not enabled for the team.

## Related Issue(s)

#4382 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: frontend/src/pages/instance/Settings/Security.vue [hunk 1]
```diff
@@ -157,7 +157,7 @@ export default {
     mounted () {
         this.checkAccess()
         this.getSettings()
-        if (this.settings.features.httpBearerTokens) {
+        if (this.settings.features.httpBearerTokens && this.team.type.properties.features.teamHttpSecurity) {
```
Comment (cstns) [inline frontend/src/pages/instance/Settings/Security.vue:160]: Please add these checks as computed props in the Features mixin `frontend/src/mixins/Features.js:2` and use the mixin instead.

**Review by cstns — CHANGES_REQUESTED** [review]

**Review by cstns — APPROVED** [review]
