### PR TITLE
fix: added missing loading state in AuditLogs

### LINKED ISSUE #5416: Some views missing a 'loading' state
### Current Behavior

Whilst demoing in Hannover on a slow network, I noticed some pages don't have a 'loading' placeholder - meaning the view shows an empty state, then suddenly populates with data. This can be misleading.

The main culprit was the various Audit Log views - but there may be others.

### Expected Behavior

Any view that loads data should have a loading placeholder to feedback to the user that things are happening

### Steps To Reproduce

1. enable chrome dev tools network throttling
2. access any audit log page

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by harshrajeevsingh**
## Description

Closes #5416 

I found that the `AuditLog` component had its own loading state, which wasn't synced with the `AuditLogBrowser` component. 

In `AuditLogBrowser`, I removed the loading variable and initialised `gettingEntries` =  `true` and passed it as a prop to `AuditLog`. Also, removed `gettingEntries` = `false` from `loadEntries()` method and instead added a _watcher_ for `logEntries` to handle gettingEntries state when the entries are updated. 

PS: BE HARSH WITH THE REVIEW & ALSO PINPOINT OTHER VIEWS WHICH I MIGHT HAVE MISSED. I'm new to this Repo, and this is my first time working with the Vue.js framework. 

Before: 

[Screencast from 2025-09-18 15-54-09.webm](https://github.com/user-attachments/assets/326a1355-5f49-4fd2-a054-13f91ea042db)

AFTER: 

[Screencast from 2025-09-18 13-26-17.webm](https://github.com/user-attachments/assets/6227f87d-681b-4710-83d0-8d4ecd080d40)

## Checklist

 - [X] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production
 - [ ] Link to Changelog Entry PR, or note why one is not needed.

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by cstns** [comment]
Thank you for your contribution!

I haven't started the review just yet but noticed an e2e test is failing:
image

If you don't have access to the GH action that's running the tests you can run them locally. Here's the [docs page](https://flowfuse.com/handbook/development/frontend/testing/#front-end-testing) to get you started.

**Comment by harshrajeevsingh** [comment]
@cstns Done! :)

**Comment by cstns** [comment]
Thank you! Will review it by EOD!

File: frontend/src/components/audit-log/AuditLogBrowser.vue [hunk 1]
```diff
@@ -112,10 +112,8 @@ export default {
         users: function (users) {
             this.auditFilters.users = users
         },
-        logEntries: function (entries) {
-            if (entries) {
-                this.gettingEntries = false
-            }
+        logEntries: function () {
```
Comment (cstns) [inline frontend/src/components/audit-log/AuditLogBrowser.vue]: Adding a watcher on logEntries could be computationally expensive dependent on how many log entries are currently loaded in the component. Moreover, this watcher will trigger when _any_ non-deep changes occur to the array, from 0 logEntries to n or from n to 100 logEntries or other superficial ones.

File: frontend/src/components/audit-log/AuditLogBrowser.vue [hunk 2]
```diff
@@ -68,8 +68,7 @@ export default {
     emits: ['load-entries'],
     data () {
         return {
-            loading: true,
-            gettingEntries: false,
+            gettingEntries: true,
```
Comment (cstns) [inline frontend/src/components/audit-log/AuditLogBrowser.vue]: by setting this property initially to true, you're just replicating the old behavior of setting loading to true when the component was created.

I'm in favor of removing duplicate state keys (`gettingEntries` and `loading`) which basically did the exact same thing but given that this project mainly uses loading in other components, I'd stick with that nomenclature

File: frontend/src/components/audit-log/AuditLogBrowser.vue [hunk 3]
```diff
@@ -153,7 +154,6 @@ export default {
                 params.append('includeChildren', includeChildren)
             }
             this.$emit('load-entries', params)
-            this.gettingEntries = false
```
Comment (cstns) [inline frontend/src/components/audit-log/AuditLogBrowser.vue:156]: given that the calls are not async, this could have been left in. It would have spared the computation ow watching `logEntries`.

File: frontend/src/components/audit-log/AuditLogBrowser.vue (hunk 1 above)
Comment (harshrajeevsingh) [reply frontend/src/components/audit-log/AuditLogBrowser.vue]: Thanks for such detailed feedback. :) 
I will remove this.

File: frontend/src/components/audit-log/AuditLogBrowser.vue (hunk 3 above)
Comment (harshrajeevsingh) [reply frontend/src/components/audit-log/AuditLogBrowser.vue:156]: This will re-create the original flicker bug. 
While the $emit call is synchronous, the action it triggers in the parent component - the API call to fetch logs, is asynchronous.

I think the component that manages the asynchronous action must manage the loading state. Wdyt? 
If you have any other suggestions, plz let me know.

Comment (cstns) [reply frontend/src/components/audit-log/AuditLogBrowser.vue:156]: Correct. The loading state should be managed outside the component, with the component only responding to those external changes

**Comment by harshrajeevsingh** [comment]
@cstns Lemme know if this looks good so that I can change other AuditLogs components too.

With these changes, the Loading overlay is shown on the first mount and whenever the EventScope changes. 

The loader on every filter change: 
I am not sure if it's required or not. I explored showing the loader for the eventType and username change, but since it's managed inside the `AuditLogBrowser` component, I found a race condition whenever the filter is changed quickly on a slow network. Another problem with implementing this could be the jarring "UI flicker" of the loading component on fast networks.

**Comment by cstns** [comment]
I owe you a review. I haven’t forgotten, but I won’t be able to get to it today.

**Comment by cstns** [comment]
This looks good. The changes are already a big improvement.

We don’t yet have a unified approach to loading states, so some flicker will remain until we rethink loaders more globally. In my view, for the `AuditLogBrowser`, the loader should only appear once on initial mount, not on every filter change, since that adds complexity and UI flicker as you noted.

Also, make sure to account for all places where `AuditLogBrowser` is used, including the admin section.

**Review by cstns — APPROVED** [review]
Looks good! 

Thanks for this contribution. Handling the audit logs loading state was long overdue, and this is as solid as it gets until we address application-wide loaders.
