### PR TITLE
Ensure target editor title doesn't get overwritten

### LINKED ISSUE #3920: Pipeline deploy is overwriting instance editor title
### Current Behavior

The title displayed in the editor is customizable via the Settings of the instance. We default it to the name of the instance, so that when a user has the editor open it is easy to identify.

As this value is stored in the instance settings object, it gets captured in a snapshot.

When a pipeline is used to deploy a snapshot between instances, the target instance gets the editor title set to the title of the source instance. This is not desirable behaviour.

### Expected Behavior

Whilst snapshots should be a complete capture of the instance settings, I think there is greater value in preserving the editor title between snapshot deploys.

I propose we handle the editor title settings as a special case that the snapshot doesn't overwrite when deployed across instances via a pipeline.

### Steps To Reproduce

 - Create pipeline between instances
 - Deploy the pipeline
 - Observe the updated title of the target instance

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### Requested By

1. https://app-eu1.hubspot.com/contacts/26586079/record/0-1/7283622371

### PR DESCRIPTION
**Pull request by hardillb**
fixes #3920

## Related Issue(s)

#3920

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: forge/db/controllers/Project.js [hunk 1]
```diff
@@ -168,7 +168,7 @@ module.exports = {
         return projectExport
     },
 
-    importProjectSnapshot: async function restoreSnapshot (app, project, snapshot, { mergeEnvVars } = { mergeEnvVars: false }) {
+    importProjectSnapshot: async function restoreSnapshot (app, project, snapshot, { mergeEnvVars, updateEditorSettings } = { mergeEnvVars: false, updateEditorSettings: true }) {
```
Comment (knolleary) [inline forge/db/controllers/Project.js:171]:
```suggestion
    importProjectSnapshot: async function restoreSnapshot (app, project, snapshot, { mergeEnvVars, mergeEditorSettings } = { mergeEnvVars: false, mergeEditorSettings: false }) {
```

File: forge/db/controllers/Project.js [hunk 2]
```diff
@@ -203,7 +203,7 @@ module.exports = {
                 }
                 const newSettings = app.db.controllers.ProjectTemplate.validateSettings(snapshotSettings, project.ProjectTemplate)
                 const currentProjectSettings = await project.getSetting('settings') || {} // necessary?
-                const updatedSettings = app.db.controllers.ProjectTemplate.mergeSettings(currentProjectSettings, newSettings, { mergeEnvVars })
+                const updatedSettings = app.db.controllers.ProjectTemplate.mergeSettings(currentProjectSettings, newSettings, { mergeEnvVars, updateEditorSettings })
```
Comment (knolleary) [inline forge/db/controllers/Project.js:206]:
```suggestion
                const updatedSettings = app.db.controllers.ProjectTemplate.mergeSettings(currentProjectSettings, newSettings, { mergeEnvVars, mergeEditorSettings })
```

File: forge/db/controllers/ProjectTemplate.js [hunk 3]
```diff
@@ -224,11 +224,17 @@ module.exports = {
    * @param {*} settings the new settings to merge in
    * @param {*} options options for the merge
    * @param {boolean} options.mergeEnvVars if true, merge the env vars (new keys added, existing keys untouched, removed keys untouched)
+   * @param {boolean} options.updateEditorSettings if true will override the current editor settings for certain keys
```
Comment (knolleary) [inline forge/db/controllers/ProjectTemplate.js:227]:
```suggestion
   * @param {boolean} options.mergeEditorSettings if false (default), will overwrite all settings. If true, it will merge the settings together - only overwriting certain ones.
```

File: forge/db/controllers/ProjectTemplate.js [hunk 4]
```diff
@@ -224,11 +224,17 @@ module.exports = {
...
    */
-    mergeSettings: function (app, existingSettings, settings, { mergeEnvVars = false } = {}) {
+    mergeSettings: function (app, existingSettings, settings, { mergeEnvVars = false, updateEditorSettings = true } = {}) {
         // Quick deep clone that is safe as we know settings are JSON-safe
         const result = JSON.parse(JSON.stringify(existingSettings))
+        const skipList = ['disableEditor', 'page_title', 'header_title']
         templateFields.forEach((name) => {
+            if (!updateEditorSettings && skipList.includes(name)) {
+                return
+            }
```
Comment (knolleary) [inline forge/db/controllers/ProjectTemplate.js:236]:
```suggestion
    mergeSettings: function (app, existingSettings, settings, { mergeEnvVars = false, mergeEditorSettings = false } = {}) {
        // Quick deep clone that is safe as we know settings are JSON-safe
        const result = JSON.parse(JSON.stringify(existingSettings))
        const skipList = ['disableEditor', 'page_title', 'header_title']
        templateFields.forEach((name) => {
            if (mergeEditorSettings && skipList.includes(name)) {
                return
            }
```

File: forge/services/snapshots.js [hunk 5]
```diff
@@ -140,6 +140,10 @@ module.exports.copySnapshot = async (
         )
     }
 
+    // // ensure the target title doesn't get overridden
+    // const targetSettings = await toInstance.getSetting('settings')
+    // snapshotToCopyProps.settings.settings.header.title = targetSettings.header.title
```
Comment (knolleary) [inline forge/services/snapshots.js:145]:
```suggestion
```

File: forge/services/snapshots.js [hunk 6]
```diff
@@ -152,7 +156,7 @@ module.exports.copySnapshot = async (
         await app.db.controllers.Project.importProjectSnapshot(
             toInstance,
             newSnapshot,
-            { mergeEnvVars: true }
+            { mergeEnvVars: true, updateEditorSettings: false }
```
Comment (knolleary) [inline forge/services/snapshots.js:159]:
```suggestion
            { mergeEnvVars: true, mergeEditorSettings: false }
```

**Review by knolleary — CHANGES_REQUESTED** [review]
I know I proposed the `updateEditorSettings` naming, but looking at it in place, it confused me. I think calling it `mergeEditorSettings` is more consistent with the other `merge...` setting. Sorry for the churn - think I've proposed all the necessary changes.

**Review by knolleary — APPROVED** [review]
