### PR TITLE
[7124] Add response-validation & surface response schema drift in dev

### LINKED ISSUE #7124: Add response-validation & surface response schema drift in dev
# Add response-validation & surface response schema drift in dev

Registers `@fastify/response-validation` when `NODE_ENV === 'development'` so schema/view drift fails loudly as a 500. Fixes the six mismatches it exposed on first run.

This PR is scoped to establishing a baseline — it adds the package, wires it up in dev mode, and fixes the drift the new validator surfaces. It does **not** add `required` arrays or `additionalProperties: false` to any schema; that work lands in a follow-up PR on top of this one.

## Fixes

| Schema | Field | Runtime reality | Fix |
|---|---|---|---|
| `Stack` / `StackSummary` | `label` | Nullable DB column, null when no label | View emits `undefined` when null (matches file's existing idiom for `projectType`, `replacedBy`) |
| `Device`, `DeviceSummary` | `ownerType` | Null until device is assigned | `nullable: true` |
| `Device` | `agentVersion` | Null until first check-in | `nullable: true` |
| `AuditLogEntry` | `username` | Null for system-triggered entries (view comment already flagged this as a compat shim) | `nullable: true` |
| `ProvisioningTokenSummary` | `targetSnapshot` | Null when the referenced snapshot was deleted; only non-nullable field in a schema where every sibling already was | `nullable: true` |
| `GET /projects/:id/devices/settings` (inline) | `targetSnapshot` | Handler explicitly returns `{ targetSnapshot: null }` when unset | `nullable: true` |
| `FlowBlueprintSummary` | `externalUrl` | Null on blueprints without external docs | `nullable: true` |
| `FlowBlueprintSummary`, `FlowBlueprintExport` | `icon` | Null on blueprints without an icon | `nullable: true` |
| `Invitation` | `role` | Nullable DB column | `nullable: true` |
| `Invitation` | `sentAt` | Null until the invite is sent | `nullable: true` |
| `InstanceType` (project-types) | `description` | Nullable DB column | `nullable: true` |
| `TeamType` | `description` | Nullable DB column | `nullable: true` |
| `PUT /teams/:teamId/devices/bulk` response | `devices[].id` | The deviceGroup branch skipped the Device view and returned raw Sequelize instances, so `id` came back as a numeric DB id instead of the hashid the schema declares | Run the collection through `Device.device()` before replying (matches what the other branches in the same handler already do) |
| `DeviceGroupPipelineSummary` | `targetSnapshotId` | View initialises to `null` and only sets a hashid when the pipeline stage has a target snapshot | `nullable: true` |
| `DeviceGroup` | `targetSnapshot` | Top-level drift: outer schema redeclared without `nullable: true`, overriding the nullable declaration inherited from `DeviceGroupSummary` via `allOf` | `nullable: true` on the outer declaration too |
| `DatabaseTable` columns | `default`, `maxLength` | Both come back as `null` for columns that have no default / no length constraint | `nullable: true` |
| `Team`, `Team` (userTeamList) | `instanceCount`, `memberCount`, `deviceCount`, `brokerCount`, `teamBrokerClientsCount` | Postgres returns COUNT(*) aggregates as strings (bigints); SQLite returns numbers — schema says `number`, SQLite passed silently, postgres failed | `parseInt(value) \|\| 0` coercion in the view |
| `TeamType` | `teamCount` | Same postgres bigint-as-string issue | `parseInt` coercion |
| `Application` (`detailed`) | `deviceCount`, `instanceCount`, `deviceGroupCount`, `snapshotCount`, `pipelineCount` | Same postgres bigint-as-string issue | `parseInt` coercion |
| `TeamApplicationList` | `applications[].instancesSummary.count`, `applications[].devicesSummary.count` | Same postgres bigint-as-string issue | `parseInt` coercion |
| `GET /teams/:teamId/brokers/team-broker/credentials` | `port`, `protocolVersion` | The team-broker synthetic response emitted `port: new URL(...).port` (a string) and `protocolVersion: '4'` (a string literal) while `MQTTBroker` declares both as numbers | Emit actual numbers: `parseInt(brokerURL.port, 10)` and the literal `4` |
| `PUT /pipelines/:pipelineId` response | `id` | Same class of bug as `/devices/bulk`: handler sent the raw Sequelize pipeline model via `reply.send(pipeline)`, so `id` came back as the numeric primary key instead of the hashid that `Pipeline` declares. The sibling POST handler at [pipeline/index.js:98](forge/ee/routes/pipeline/index.js#L98) already used the view. | `reply.send(await app.db.views.Pipeline.pipeline(pipeline))` |

`frontend/src/types/generated.ts` picks up 20 fields total with `| null`. `npm run test:unit:frontend` and `npm run build` pass with no downstream changes. The `parseInt` coercions don't change types (schemas were already `number`; they just now actually receive numbers on postgres too).

## Test plan

<details><summary> ✅ All tests passed! </summary>

- [x] **`NODE_ENV=development npm run test:system`** — 61 passing, 0 failing, 0 validator errors.
- [ ] **`npm run test:unit:forge`** — locally hits a pre-existing native `async_hooks` crash in EE MQTT/billing setup on Node 20.19.5, unrelated (the validator doesn't run during unit tests — `NODE_ENV` isn't `development`). Rely on CI.
- [x] **`npm run generate:types` + `npm run test:unit:frontend` + `npm run build`** — 14-line types diff (7 fields gain `| null`), no TS errors, no code changes needed.
- [x] **Manual dev browser test** — boot `NODE_ENV=development npm run serve`, click through every page; any 500 with `FST_RESPONSE_VALIDATION_FAILED_VALIDATION` is drift.

  **Endpoints exercised (all 200):**

  OS:
  - [x] `GET /api/v1/templates`, `/templates/:id`
  - [x] `GET /api/v1/user/invitations`, `/user/notifications`, `/user/tokens`, `/user/`, `/user/teams`
  - [x] `GET /api/v1/teams/:teamId/audit-log`, `/projects/:id/audit-log`, `/applications/:id/audit-log`, `/admin/audit-log`
  - [x] `GET /api/v1/teams/:teamId/devices/provisioning`

  EE:
  - [x] `GET /api/v1/applications/:id/pipelines` (team-level `/teams/:id/pipelines` also clean)
  - [x] `GET /api/v1/flow-blueprints`, `/flow-blueprints/:id`
  - [x] `GET /api/v1/teams/:teamId/databases`, `/databases/:id`, `/databases/:id/tables`
  - [x] `GET /api/v1/teams/:teamId/mcp`
  - Note: `GET /api/v1/pipelines/:id` doesn't exist (only POST/PUT/DELETE on that path). `Pipeline` schema covered via the list endpoint.

  Bonus (implicit coverage, all 200):
  - [x] `/admin/license`, `/admin/stats`, `/settings`, `/users`, `/project-types`, `/stacks`, `/team-types`, `/teams`
  - [x] `/teams/:id`, `/teams/slug/:slug`, `/teams/:id/{applications,members,user,projects,bom,invitations,device-groups,devices,git/tokens,instance-counts,broker/clients,brokers,brokers/:id,brokers/:id/topics}`
  - [x] `/applications/:id`, `/applications/:id/{bom,devices,instances,snapshots}`
  - [x] `/projects/:id`, `/projects/:id/status`, `/projects/:id/devices/settings` (post-fix #6)

</details>

## Risk

Low. Prod is unaffected — every new line is under the `NODE_ENV === 'development'` gate. `nullable: true` additions don't change the wire (fast-json-stringify was already emitting null). Only shape change: `ProjectStack.label` is now omitted when null instead of `"label": null`; frontend already treats it as optional (`label?: string`).

### PR DESCRIPTION
**Pull request by n-lark**
## Description

This is a subtask of https://github.com/FlowFuse/flowfuse/issues/7083. 

> This PR is scoped to establishing a baseline — it adds the package, wires it up in dev mode, and fixes the drift the new validator surfaces. It does not add required arrays or additionalProperties: false to any schema; that work lands in a follow-up PR on top of this one.

## Related Issue(s)

Resolves https://github.com/FlowFuse/flowfuse/issues/7124

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production
 - [ ] Link to Changelog Entry PR, or note why one is not needed.

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: forge/routes/api/teamDevices.js [hunk 1]
```diff
@@ -579,6 +579,8 @@ module.exports = async function (app) {
                     { info: infoBuilder.join(', ') })
 
                 // we're not sending the updated devices back, the FE will fetch the updated list of devices separately
+                // but run them through the view so the shape matches the declared schema.
+                devicesCollection.devices = devicesCollection.devices.map(d => app.db.views.Device.device(d))
```
Comment (cstns) [inline forge/routes/api/teamDevices.js:583]: nice catch

File: package.json [hunk 2]
```diff
@@ -82,6 +83,7 @@
         "@sentry/vue": "^7.91.0",
         "@sentry/webpack-plugin": "^2.7.1",
         "@vuepic/vue-datepicker": "^11.0.2",
+        "ajv": "8.18.0",
```
Comment (cstns) [inline package.json]: shouldn't it be a dev dependency?

File: package.json [hunk 3]
```diff
@@ -63,6 +63,7 @@
         "@fastify/multipart": "^9.3.0",
         "@fastify/passport": "^3.0.2",
         "@fastify/rate-limit": "^10.3.0",
+        "@fastify/response-validation": "3.0.3",
```
Comment (cstns) [inline package.json]: the same for this, shouldn't it be a dev dependency?

File: forge/ee/routes/pipeline/index.js [hunk 4]
```diff
@@ -204,7 +204,7 @@ module.exports = async function (app) {
             await app.auditLog.Team.application.pipeline.updated(request.session.User, null, team, request.application, pipeline, updates)
         }
 
-        reply.send(pipeline)
+        reply.send(await app.db.views.Pipeline.pipeline(pipeline))
```
Comment (cstns) [inline forge/ee/routes/pipeline/index.js:207]: good catch

File: forge/routes/index.js [hunk 5]
```diff
@@ -21,6 +21,57 @@ module.exports = fp(async function (app, opts) {
...
+        const Ajv = require('ajv')
+        const ajv = new Ajv({
+            coerceTypes: false,
+            useDefaults: true,
+            removeAdditional: true,
+            allErrors: true,
+            strict: false
+        })
+        // Convert OpenAPI `nullable: true` to JSON Schema — Ajv doesn't understand the keyword.
+        const stripNullable = (value) => {
```
Comment (cstns) [inline forge/routes/index.js:37]: why can't we fully rely on ajv's built in nullable support? v8 should already support open-api style keywords in many common cases.

**Review by cstns — COMMENTED** [review]
looking good overall, just a few questions here and there

File: forge/routes/index.js (hunk 5 above)
Comment (n-lark) [reply forge/routes/index.js:37]: So what I ran into was Ajv v8 handles `nullable: true` when it sits alongside an inline `type`. But it explicitly throws `"nullable" cannot be used without "type"` on the `{ nullable: true, allOf: [{ $ref: 'stuff' }] }` form, which we use throughout the codebase for nullable references like `Device.activeSnapshot`, `DeviceGroup.targetSnapshot` etc.

Adding an inline `type: 'object`' to those refs doesn't fix it either, it compiles, but rejects `null` at runtime, because `allOf` still runs every subschema and the referenced schema isn't nullable.

`stripNullable` rewrites both forms into `anyOf: [{...}, { type: 'null' }]` so the ref pattern actually validates.

File: package.json (hunk 2 above)
Comment (n-lark) [reply package.json]: Moved! ty!

File: package.json (hunk 3 above)
Comment (n-lark) [reply package.json]: ditto moved

**Review by cstns — APPROVED** [review]
