### PR TITLE
Ensure Valkey/Redis cache reconnects cleanly

### LINKED ISSUE #6777: Forge app can crash if Valkey server restarts
### Current Behavior

Forge app can fail if Valkey server is lost

### Expected Behavior

Forge app continues to run and periodically attempts to reconnect

### Steps To Reproduce

- Start forge app with valkey cache enabled
- restart valkey

### Environment

- FlowFuse version: 2.27.1
- Node.js version: 20
- npm version: 10.x
- Platform/OS: all
- Browser: all

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by hardillb**
fixes #6777

## Description

Adds error handlers and a reconnect stategy as well as upgrading @redis/client package

## Related Issue(s)

#6777

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production
 - [ ] Link to Changelog Entry PR, or note why one is not needed.

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
`error` callback is needed for reconnect logic to run, but doesn't need to do anything, hence the lint tag

File: forge/caches/redis-cache.js [hunk 1]
```diff
@@ -5,8 +5,29 @@ const caches = {}
...
+            reconnectStrategy: (retries, cause) => {
+                // Generate a random jitter between 0 – 200 ms:
+                const jitter = Math.floor(Math.random() * 200)
+                // Delay is an exponential back off, (times^2) * 50 ms, with a maximum value of 2000 ms:
+                const delay = Math.min(Math.pow(2, retries) * 50, 2000)
+                return delay + jitter
+            }
+        }
+    }
+    client = createClient(newOptions)
```
Comment (knolleary) [inline forge/caches/redis-cache.js:20]: We ought to have some app level logging here around the connection state.

Comment (hardillb) [reply forge/caches/redis-cache.js:20]: Yeah, we probably should, but that was a bigger change to pass in the `app` object to get hold of the logging stuff.

Will add after team meeting

Comment (hardillb) [reply forge/caches/redis-cache.js:20]: @knolleary logging added, should be ready for re-review
