### PR TITLE
Enrich crash email with detail and hints where crash reason can be inferred  

### LINKED ISSUE #4934: Use launcher exit info to improve "Instance Crashed" email

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #4934

## Description

* passes crash detail from API to postoffice routine
* checks/infers the 2 suggested stop reasons from the data:
    * out of memory
    * unhandled exception
* Adds 2 email templates for these conditions with each one including specific extra info:
   * possible reasons
   * possible solutions
   * last (max) 20 log entries 
* Updates the generic Crash template to also display last (max) 20 log entries (only displayed if the context data includes logs) 

### Screenshots

image

image

image

## Related Issue(s)

owner: #4934 
parent: https://github.com/FlowFuse/flowfuse/issues/4653

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@joepavitt added as 2nd reviewer for the visual aspect

**Comment by Steve-Mcl** [comment]
Added tests:

```
  Instance Alerts emails
    Alerts
      ✔ Crashed, via api (no logs) (79ms)
      ✔ Crashed, generic, via api (including logs)
      ✔ Crashed, out-of-memory, via api (including logs) (51ms)
      ✔ Crashed, uncaught-exception, via api (including logs) (42ms)
```

**Review by joepavitt — APPROVED** [review]

File: test/unit/forge/ee/lib/alerts/alerts_spec.js [hunk 1]
```diff
@@ -35,12 +38,133 @@ describe('Instance Alerts emails', function () {
...
+                }
+            })
+            response.statusCode.should.equal(200)
+
+            inbox.messages.should.have.length(1)
+            // use regex to ensure there is <p>\n.*Logs...
+            inbox.messages[0].html.should.match(/<p>\n.*Logs\.\.\./)
+            inbox.messages[0].html.should.match(/<td>info message 1<\/td>/)
+            inbox.messages[0].html.should.match(/<td>v8::internal::heap::<\/td>/)
+            inbox.messages[0].text.should.match(/\n.*Logs\.\.\./)
```
Comment (knolleary) [inline test/unit/forge/ee/lib/alerts/alerts_spec.js:140]:
```suggestion
            // use regex to ensure there is <p>\n.*Logs:
            inbox.messages[0].html.should.match(/<p>\n.*Logs:/)
            inbox.messages[0].html.should.match(/<td>info message 1<\/td>/)
            inbox.messages[0].html.should.match(/<td>v8::internal::heap::<\/td>/)
            inbox.messages[0].text.should.match(/\n.*Logs:/)
```

File: test/unit/forge/ee/lib/alerts/alerts_spec.js [hunk 2]
```diff
@@ -51,7 +175,21 @@ describe('Instance Alerts emails', function () {
                 }
             })
             response.statusCode.should.equal(200)
+
             inbox.messages.should.have.length(1)
+            inbox.messages[0].html.should.match(/<p>\n.*Logs\.\.\./)
+            inbox.messages[0].html.should.match(/<td>info message 1<\/td>/)
+            inbox.messages[0].html.should.match(/<td>uncaught exception<\/td>/)
+            inbox.messages[0].text.should.match(/\n.*Logs\.\.\./)
```
Comment (knolleary) [inline test/unit/forge/ee/lib/alerts/alerts_spec.js:183]:
```suggestion
            inbox.messages[0].html.should.match(/<p>\n.*Logs:/)
            inbox.messages[0].html.should.match(/<td>info message 1<\/td>/)
            inbox.messages[0].html.should.match(/<td>uncaught exception<\/td>/)
            inbox.messages[0].text.should.match(/\n.*Logs:/)
```

**Review by knolleary — APPROVED** [review]
Approved - although have proposed changing the email content `Logs...` to `Logs:` as more of a header.
