### PR TITLE
Show "Expired" for expired licenses

### LINKED ISSUE #4889: Admin summary page shows time since license expired as remaining
### Current Behavior

This license expired at midnight

image

### Expected Behavior

To show time since expired (or to just say expired)

### Steps To Reproduce

Run FF with an expired license

### Environment

- FlowFuse version: 2.11.0
- Node.js version: all
- npm version: all 
- Platform/OS: all
- Browser: all

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by hardillb**
fixes #4889

## Description

Admin overview showed "Expires: 2025-01-01" even when license has already expired, implying there was time left.

Now shows "Expied: 2024-01-01" after license has expired.

## Related Issue(s)

 #4889

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: frontend/src/pages/admin/Overview.vue [hunk 1]
```diff
@@ -112,13 +112,17 @@ export default {
...
+            expired: false
         }
     },
     async mounted () {
         try {
             this.stats = await adminApi.getStats()
             this.license = await adminApi.getLicenseDetails()
+            if (this.license?.expiresAt && (Date.parse(this.license.expiresAt) - Date.now()) < 0) {
+                this.expired = true
+            }
```
Comment (ZJvandeWeg) [inline frontend/src/pages/admin/Overview.vue:125]:
```suggestion
            this.expired = this.license?.expiresAt && (Date.parse(this.license.expiresAt) - Date.now()) < 0
```

**Review by ZJvandeWeg — APPROVED** [review]

**Comment by ZJvandeWeg** [comment]
@hardillb One style nitpick, but happy to be ignored and this to be merged as is.
