### PR TITLE
fix pipelinestage device action dropdown choices

### LINKED ISSUE #3109: Pipeline stage permits action "Create new snapshot"
### Current Behavior

Possible to have a Stage Type "Device" with action type "Create snapshot"
chrome_oxljfS7SJm

### Expected Behavior

Dropdown should NOT include "create snapshot" when the stage type is "device"

### Steps To Reproduce

* Select stage type instance
* choose item "Create Snapshot" in the "select action"
* Select "stage type" "device"

You will see the "select action" dropdown keeps the invalid choice "Create Snapshot"

### Environment

- FlowForge version: 1.13.x-git
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by Steve-Mcl**
fixes #3109

## Description

Reset Select Action dropdown if the stage type is "Device" and the "Select Action" is an invalid choice

See a demo in the issue

## Related Issue(s)

#3109 

### Verify

1. Select stage type instance
2. choose item "Create Snapshot" in the "select action" 
3. Select "stage type" "device"
4. See how "select action" still says "Create Snapshot"
   1. This should revert to the top option

### CODE REVIEW

File: frontend/src/pages/application/PipelineStage/form.vue [hunk 1]
```diff
@@ -343,6 +343,16 @@ export default {
             return options
         }
     },
+    watch: {
+        'input.stageType': {
+            handler (_stageType) {
+                // if the stage type is changed, ensure the action is NOT "create_snapshot" when the stage type is "device"
+                if (this.input.stageType === StageType.DEVICE && this.input.action === 'create_snapshot') {
+                    this.input.action = 'use_latest_snapshot' // set default action for device stage
```
Comment (Pezmc) [inline frontend/src/pages/application/PipelineStage/form.vue:351]: I'd make this slightly more dynamic and pull the top option from the list, will make the change myself for speed!

**Comment by Pezmc** [comment]
I've updated it to reset the selection to whatever was set on the stage originally, which means the placeholder shows again or it returns to the previously selected value, this is slightly nicer when swapping back and forth .

**Review by joepavitt — APPROVED** [review]

**Comment by Pezmc** [comment]
https://github.com/FlowFuse/flowfuse/assets/507155/ce8eeecc-3ba7-4bd4-a232-1041d2e21f28

**Comment by Pezmc** [comment]
Verified on staging.
