### PR TITLE
Fix snapshot diff viewer highlights and diff panel

### LINKED ISSUE #7062: Snapshot DIff View: Investigate failure points
### Description

Follow-up to epic #7029 — fixes and improvements for the snapshot diff view, leveraging new capabilities from flow-renderer (FlowFuse/flow-renderer#94).

### Changes

**Highlight & navigation improvements:**
- Use `persistentHighlight: true` so highlights stay until the user navigates to the next change (instead of auto-clearing after 10s)
- Use `clearHighlight()` API to clear previous highlight before applying the next one — fixes stale highlights when navigating from a canvas node to a config node
- Use `allChanges: true` so the renderer returns change entries (with `highlight()`) for all changed nodes, including position-only changes
- Skip highlighting for config nodes (global and flow-scoped) that have no visual presence on the canvas

**Config node handling:**
- Detect config nodes by absence of `x`/`y` coordinates — works universally across all node packages
- Show "Global Config" / "Flow Config" badge in the navigation bar
- Resolve `g` (group) property to the group's display name

**Diff panel improvements:**
- Ignore `w` and `h` properties in `computeDiff` — these are computed by Node-RED at render time, not user data
- Add "Simple view" toggle that hides position (`x`, `y`) changes and drops nodes with only position diffs
- Add word wrap toggle for long diff lines
- Add Prettify/Raw toggle for JSON string values
- Capitalize labels (Tab, Group, Status) and diff type badges
- Add `g` (group) to compact props

### Dependency

Requires FlowFuse/flow-renderer#94 (`persistentHighlight`, `clearHighlight()`, `allChanges` options).

Both new options pass harmlessly through `normaliseOptions` on older renderer versions (ignored as extra properties), so there is no hard version gate — highlights simply fall back to auto-clear behaviour.

### Epic/Story

#7029

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

### LINKED ISSUE #7073: Snapshot Diff: Use flow-renderer persistentHighlight instead of auto-clearing highlights
### Description

The flow-renderer's `compare()` auto-clears node and tab glow highlights after 10 seconds. In the snapshot diff viewer, the user navigates between changes and needs highlights to persist until moving to the next one.

### Changes

- Pass `persistentHighlight: true` to `flowRenderer.compare()`
- Store `clearHighlight` reference from the comparison result for manual cleanup (falls back to no-op on older renderer versions)

### Dependencies

- FlowFuse/flow-renderer#91

### Parent issue

Part of #7062

### LINKED ISSUE #7074: Snapshot Diff: Skip highlighting for config nodes and clear previous glow
### Description

When navigating to a global-config or flow-config node in the snapshot diff viewer, the previous node's glow highlight remains visible because config nodes have no visual presence on the SVG canvas and nothing triggers a new highlight to replace the old one.

### Changes

- Add `nodeCategory()` helper to classify nodes as tab, group, subflow, global-config, flow-config, or regular node
- Add `CONFIG_CATEGORIES` constant for categories without SVG presence
- When navigating to a config node, call `clearRendererHighlight()` to remove the previous glow
- Show "Global Config" / "Flow Config" purple badge in the nav bar via `currentGroupCategoryLabel` computed property

### Parent issue

Part of #7062

### LINKED ISSUE #7075: Snapshot Diff: Ignore computed properties (w, h) in diff
### Description

The snapshot diff shows `w` and `h` as changed properties. These values are computed by Node-RED at render time and are not user data, so differences in them are noise.

### Changes

- Add `IGNORED_PROPS` constant (`id`, `w`, `h`) and use it in `computeDiff` to skip these properties

### Parent issue

Part of #7062

### LINKED ISSUE #7076: Snapshot Diff: Resolve group ID and improve property labels in diff sidebar
### Description

The `g` property (group membership) is displayed as a raw UUID in the diff sidebar. Other property labels are inconsistently cased.

### Changes

- Add `resolveNodeName()` to look up group IDs and display human-readable names
- Handle `g` property in `transformChanges` with label "Group" (compact mode)
- Add `g` to `COMPACT_PROPS` set
- Capitalize labels: "tab" → "Tab", "status" → "Status"

### Parent issue

Part of #7062

### LINKED ISSUE #7077: Snapshot Diff: Add wrap toggle and JSON prettify to diff change panel
### Description

The diff change panel (`SnapshotDiffChangePanel.vue`) has no way to handle long lines or JSON-formatted string values, making some property diffs hard to read.

### Changes

- Add "Wrap" toggle button, shown when any diff line exceeds 50 characters
- Add "Prettify" button for JSON-like string values — parses, pretty-prints with indentation, and re-diffs
- Add "Raw" button to revert to the original un-prettified diff
- Improve scroll container CSS (`diff-scroll-container`) for proper horizontal scrolling when wrap is off

### Parent issue

Part of #7062

### PR DESCRIPTION
**Pull request by andypalmi**
## Summary

- Use `persistentHighlight` and `clearHighlight()` from flow-renderer so highlights persist until navigation and stale glows are cleared
- Use `allChanges` option so all changed nodes get `highlight()` entries
- Skip highlighting for config nodes (no canvas presence); show "Global Config" / "Flow Config" badge
- Detect config nodes by absence of `x`/`y` coordinates — works for all node packages
- Ignore `w`/`h` in `computeDiff` (computed by Node-RED at render time)
- Add "Simple view" toggle to hide position changes
- Add word wrap and Prettify/Raw toggles in the diff panel
- Resolve group (`g`) property to display name; capitalize labels

Depends on FlowFuse/flow-renderer#94

Closes #7062 
Closes #7073
Closes #7074
Closes #7075
Closes #7076
Closes #7077

## Test plan

- [ ] Compare two snapshots — verify highlights persist when navigating between changes
- [ ] Navigate to a config node (e.g. mqtt-broker) — verify no highlight attempt, "Flow Config" or "Global Config" badge shown
- [ ] Toggle "Simple view" — verify position-only nodes are hidden and x/y props disappear
- [ ] Expand a diff panel with long lines — verify "Wrap" toggle works
- [ ] Expand a diff panel with JSON string values — verify "Prettify" / "Raw" toggle works
- [ ] Verify w/h changes do not appear in the diff

### CODE REVIEW

**Review by Steve-Mcl — COMMENTED** [review]
couple of minor points

File: frontend/src/components/dialogs/SnapshotDiffChangePanel.vue [hunk 1]
```diff
@@ -139,11 +170,43 @@ export default {
...
+            if (!this.compact) {
+                this.prettified = false
+                this.lines = this.buildLines(this.value1, this.value2)
+            }
         },
-        buildLines () {
-            const v1 = this.stringify(this.value1)
-            const v2 = this.stringify(this.value2)
+        looksLikeJson (v) {
+            if (typeof v === 'string' && v.length > 2) {
```
Comment (Steve-Mcl) [inline frontend/src/components/dialogs/SnapshotDiffChangePanel.vue:179]: `[]` is 2 characters. `{}` is 2 characters. Both are valid JSON.

File: frontend/src/components/dialogs/SnapshotDiffChangePanel.vue [hunk 2]
```diff
@@ -139,11 +170,43 @@ export default {
...
+                const c = v[0]
+                return c === '{' || c === '['
```
Comment (Steve-Mcl) [inline frontend/src/components/dialogs/SnapshotDiffChangePanel.vue:181]: This would fail if spaces are present. Also, I would test if the last character matches the opposite bracket.

File: frontend/src/components/dialogs/SnapshotDiffChangePanel.vue [hunk 3]
```diff
@@ -139,11 +170,43 @@ export default {
...
+            }
+            return false
+        },
+        tryPrettify (v) {
+            if (typeof v === 'string' && v.length > 2 && (v[0] === '{' || v[0] === '[')) {
```
Comment (Steve-Mcl) [inline frontend/src/components/dialogs/SnapshotDiffChangePanel.vue:186]: Why repeat code & not use the `looksLikeJson` function?

**Review by Steve-Mcl — COMMENTED** [review]
actually add the review items this time :doh:

File: frontend/src/components/dialogs/SnapshotDiffChangePanel.vue (hunk 1 above)
Comment (andypalmi) [reply frontend/src/components/dialogs/SnapshotDiffChangePanel.vue]: Fixed in 622655e — changed to `>= 2`.

File: frontend/src/components/dialogs/SnapshotDiffChangePanel.vue (hunk 2 above)
Comment (andypalmi) [reply frontend/src/components/dialogs/SnapshotDiffChangePanel.vue]: Fixed in 622655e — now trims whitespace and checks that the last character is the matching closing bracket.

File: frontend/src/components/dialogs/SnapshotDiffChangePanel.vue (hunk 3 above)
Comment (andypalmi) [reply frontend/src/components/dialogs/SnapshotDiffChangePanel.vue]: Fixed in 622655e — `tryPrettify` now calls `looksLikeJson` instead of duplicating the check.

File: frontend/src/components/dialogs/AssetCompareDialog.vue [hunk 4]
```diff
@@ -150,7 +172,8 @@ export default {
             sidebarWidth: 380,
             resizing: false,
             resizeStartX: 0,
-            resizeStartWidth: 0
+            resizeStartWidth: 0,
+            hidePositionChanges: false
```
Comment (n-lark) [inline frontend/src/components/dialogs/AssetCompareDialog.vue:176]: Do we wanna reset this in `show()` too? Otherwise the Simple view toggle persists across dialog reopens.

File: frontend/src/components/dialogs/SnapshotDiffChangePanel.vue [hunk 5]
```diff
@@ -35,12 +35,36 @@
...
-                <span class="ml-auto text-gray-400">{{ changeSummary }}</span>
+                <span class="ml-auto flex items-center gap-2">
+                    <template v-if="!collapsed">
+                        <!-- Wrap toggle (shown when any line exceeds 50 chars) -->
+                        <button
+                            v-if="hasLongLines"
+                            class="text-gray-400 hover:text-gray-600 px-1 py-0.5 rounded hover:bg-gray-200"
+                            title="Toggle word wrap"
+                            @click.stop="wrapped = !wrapped"
+                        >Wrap</button>
```
Comment (n-lark) [inline frontend/src/components/dialogs/SnapshotDiffChangePanel.vue:48]: We could add some styling here for pressed/not pressed to give user visual feedback. Similar to Simple view button.

**Review by n-lark — APPROVED** [review]
Minor things looks good!

File: frontend/src/components/dialogs/AssetCompareDialog.vue (hunk 4 above)
Comment (andypalmi) [reply frontend/src/components/dialogs/AssetCompareDialog.vue:176]: I think it'd be better UX if we keep it, what do you think? @n-lark

Comment (andypalmi) [reply frontend/src/components/dialogs/AssetCompareDialog.vue:176]: > Simple view toggle persists across dialog reopens.

It would allow for exactly this behaviour, a sort of user config on how to view snapshots

Comment (n-lark) [reply frontend/src/components/dialogs/AssetCompareDialog.vue:176]: User preference makes sense to me.
