### PR TITLE
Fix the env var table for admin view & update the admin views to use ff-page

### LINKED ISSUE #5398: Trying to add Env var to template (as admin) fails
### Current Behavior

Clicking on the  "+ Add variable" button breaks the table of env vars and doesn't allow a new one to be added

Image

click "+ Add variable" button

Image

### Expected Behavior

A new row should be added to the table to allow entering new env var

### Steps To Reproduce

as admin, open a template
pick Environment tab
click on "+ Add Variable" button

### Environment

- FlowFuse version: 2.15.1
- Node.js version: 18.x
- npm version: 9.x
- Platform/OS: All
- Browser: All

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- Modifies the env var table to create a local copy of the "original" env vars if one isn't passed to it.
- Whilst fixing that, realised the at this was a lot more difficult because none for the admin pages had been updated to use `ff-page`, so dove into updating them all whilst there. Removes the need for a lot of custom CSS, overrides, etc, and ensures consistent layouts across the platform
    - Includes removing deprecated `ff-instance-header` and `clear-page-gutters` CSS classes too

## Related Issue(s)

Closes #5398

### CODE REVIEW

File: frontend/src/pages/admin/NotificationsHub.vue [hunk 1]
```diff
@@ -1,84 +1,82 @@
...
+                            <input v-model="form.teamTypes" type="checkbox" :value="teamType.id" @keydown.space.prevent>
+                            {{ teamType.name }}
+                        </label>
+                    </div>
+                    <template v-if="features.billing">
+                        <FormHeading class="mt-4">Billing State:</FormHeading>
                         <div class="grid gap-1 grid-cols-2 items-middle">
                             <label
-                                v-for="(role, $key) in roleIds"
+                                v-for="(billingState, $key) in billingStates"
```
Comment (joepavitt) [inline frontend/src/pages/admin/NotificationsHub.vue:59]: These changes are misleading in the diff - given we lost loads of code, the alignment means the diff thinks these changed from `roleIds` to `billingStates`, but it is just a shift of code up the file

**Comment by Steve-Mcl** [comment]
Unfortuately there is more wrong.  Secrets do not work either:

### Current condition:
* Secret toggle state is lost upon save
* Toggling secret does not enable <kbd>save changes</kbd>
chrome_JxOxh7D39v


### Expected condition (instances/devices)
* Toggling secret enables <kbd>save</kbd>
* Upon saving a secret, it is blurred
* Refreshing page should not return the secret value
chrome_5ulL1GIdwK

**Comment by Steve-Mcl** [comment]
Sorry Joe. I just realised I was never asked to review this PR 😊 

_Off I go to review the correct one now_ 🏃‍♂️

**Comment by hardillb** [comment]
@cstns are you likely to get to this before release tomorrow?

**Comment by cstns** [comment]
yes, actively working on it!

**Review by hardillb — APPROVED** [review]
