### PR TITLE
Fix: Loading project snapshot for every device status update

### LINKED ISSUE #2980: N+1 Query: Project snapshot in /api/comms/auth/acl
Sentry Issue: [FLOWFUSE-BACKEND-P](https://flowfuse.sentry.io/issues/4551514656/?referrer=github_integration)
|  |  |
| ------------- | --------------- |
| **Offending Spans** | db - SELECT "id", "name", "description", "setti... 

```sql
UPDATE Devices SET lastSeenAt=CURRENT_TIMESTAMP,activeSnapshotId=$1,updatedAt=$2
WHERE id = $3
```
Repeating Spans (24)	
```sql
SELECT id, name, description, settings, flows, createdAt, updatedAt, ProjectId, DeviceId, UserId
FROM ProjectSnapshots AS ProjectSnapshot
WHERE ProjectSnapshot.id IN (
  1486
)
LIMIT 1;
```

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

Previously every device status update resulted in pulling a full project snapshot object from the database.

This PR changes that to:
 - Only load the snapshot if the snapshot ID has changed
 - Use count rather then loading the full object for the times it has changed

Includes green/green test coverage too confirm no change in behaviour.

## Related Issue(s)

Fixes #2980

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: forge/db/controllers/Device.js [hunk 1]
```diff
@@ -14,16 +14,17 @@ module.exports = {
...
             const snapshotId = app.db.models.ProjectSnapshot.decodeHashid(state.snapshot)
             // hashid.decode returns an array of values, not the raw value.
-            if (snapshotId?.length > 0) {
-                // check to see if snapshot still exists
-                if (await app.db.models.ProjectSnapshot.byId(state.snapshot)) {
-                    device.set('activeSnapshotId', snapshotId)
+            if (snapshotId?.length > 0 && snapshotId !== device.activeSnapshotId) {
+                // Check to see if snapshot exists
+                if (await app.db.models.ProjectSnapshot.count({ where: { id: snapshotId }, limit: 1 }) > 0) {
+                    device.set('activeSnapshotId', snapshotId[0])
```
Comment (Pezmc) [inline forge/db/controllers/Device.js:23]: One thing of note, I'm surprised this was ever working, previously it was being called with: `device.set('activeSnapshotId', [1])`, which would be trying to set the ID to an array.

Comment (knolleary) [reply forge/db/controllers/Device.js:23]: Sequelize has always appeared to do the right thing when passes an array when expecting a simple value. I've looked at this a couple times in the past and convinced myself all was okay.

**Review by knolleary — APPROVED** [review]
