### PR TITLE
Rate limit AutoStackUpdate task

### LINKED ISSUE #6872: Need to rate limit instance restart as part of Scheduled maintenance
### Current Behavior

All instances in a given hour are suspened/updated/restated with no delay between tasks or instances.

This can overwelm the backend container driver when large numbers of instances need restarting

### Expected Behavior

There should be a pause between suspend and restart and between each instance to reduce load on container driver.

### Steps To Reproduce

schedule large number of instances for upgrade.

### Environment

- FlowFuse version: 2.28.0
- Node.js version: 20
- npm version: 10
- Platform/OS: all
- Browser: all

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by hardillb**
fixes #6872

## Description

This adds a 1 second delay between suspend and restart and another 1 second after each instance in the list.

It also no longer tries to upgrade suspended instances.

## Related Issue(s)

#6872 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production
 - [ ] Link to Changelog Entry PR, or note why one is not needed.

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
Do we have insight on what the api rate limits are? Adding these delays will slow down the calls we make, but not deal with the overall volume. Is the retry handling going into the driver separately? It feels like this code should leave a previously running instance in suspended state - but is it this code's responsibility or the drivers?

File: forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js [hunk 1]
```diff
@@ -18,41 +21,50 @@ module.exports = {
...
-                            const result = await suspendProject(project.Project, suspendOptions)
+                                app.db.controllers.Project.setInflightState(project.Project, 'starting')
+                                const result = await suspendProject(project.Project, suspendOptions)
 
-                            await project.Project.setProjectStack(newStack)
-                            await project.Project.save()
+                                await project.Project.setProjectStack(newStack)
+                                await project.Project.save()
+                                // Give time for k8s to settle after suspend
+                                await delay(1000)
```
Comment (hardillb) [inline forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js]:
```suggestion
                                await delay(2000)
```

File: forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js [hunk 2]
```diff
@@ -18,41 +21,50 @@ module.exports = {
...
-                            project.Project.state = 'running'
-                            await project.Project.save()
-                            await app.containers.restartFlows(project.Project)
-                            await app.auditLog.Project.project.restarted(null, null, project.Project)
-                            await app.db.controllers.Project.clearInflightState(project.Project)
-                        } catch (err) {
-                            app.log.info(`Problem restarting project ${project.Project.id} - ${err.toString()}`)
+                                await unSuspendProject(project.Project, result.resumeProject, result.targetState)
+                                // Space out restarts a little to not overwhelm k8s api
+                                await delay(1000)
```
Comment (hardillb) [inline forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js]:
```suggestion
                                await delay(2000)
```

File: forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js [hunk 3]
```diff
@@ -18,41 +21,50 @@ module.exports = {
...
+                            try {
+                                app.log.info(`Restarting project ${project.Project.id} as scheduled`)
+                                await app.db.controllers.Project.setInflightState(project.Project, 'restarting')
+                                project.Project.state = 'running'
+                                await project.Project.save()
+                                await app.containers.restartFlows(project.Project)
+                                await app.auditLog.Project.project.restarted(null, null, project.Project)
+                                await app.db.controllers.Project.clearInflightState(project.Project)
+                                // space out the Node-RED restarts a little.
+                                await delay(500)
```
Comment (hardillb) [inline forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js]:
```suggestion
                                await delay(1000)
```

**Review by hardillb — COMMENTED** [review]
Doubling the pauses to just really be sure

**Comment by hardillb** [comment]
@knolleary doubles the waits

File: forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js [hunk 4]
```diff
@@ -18,41 +21,50 @@ module.exports = {
...
+                            try {
+                                app.log.info(`Restarting project ${project.Project.id} as scheduled`)
+                                await app.db.controllers.Project.setInflightState(project.Project, 'restarting')
+                                project.Project.state = 'running'
+                                await project.Project.save()
+                                await app.containers.restartFlows(project.Project)
+                                await app.auditLog.Project.project.restarted(null, null, project.Project)
+                                await app.db.controllers.Project.clearInflightState(project.Project)
+                                // space out the Node-RED restarts a little.
+                                await delay(1000)
```
Comment (knolleary) [inline forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js]:
```suggestion
                                await delay(2000)
```

Missed one

Comment (hardillb) [reply forge/ee/lib/autoUpdateStacks/tasks/upgrade-stack.js]: That used to be 500, but this is just restarting nr inside the running container so only load on the `/api/v1/projects/<id>/settings endpoint.

But no problem in making them match
