### PR TITLE
Stop automatically clearing device group target when empty

### LINKED ISSUE #6169: Removing last member of a Device Group removes the target snapshot
### Current Behavior

>I 'm noticing, is that the moment the last device is removed from a device group, the target snapshot entirely disappears. This, to me, sounds like unexpected behavior. 

### Expected Behavior

Device group should retain it's target snapshot and apply it to new devices when they are added to the group

### Steps To Reproduce

_No response_

### Environment

- FlowFuse version: 2.22.0
- Node.js version: 20.x
- npm version: 10.x
- Platform/OS: FFC
- Browser: All

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by hardillb**
fixes #6169

## Description

Instead of automatically clearing the target snapshot of a group when the last device is removed, now ask the user if they want to clear it.

## Related Issue(s)

#6169

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production
 - [ ] Link to Changelog Entry PR, or note why one is not needed.

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
Failed a BluePrint UI test that should not have been impacted by this. Will re-run

File: frontend/src/pages/application/DeviceGroup/devices.vue [hunk 1]
```diff
@@ -331,7 +331,7 @@ export default {
             const addedCount = devicesAdded.length
             const warning = []
             if (addedCount > 0) {
-                warning.push('1 or more devices will be added to this group. These device(s) will be updated to deploy the active pipeline snapshot.')
+                warning.push('1 or more devices will be added to this group. These device(s) will be updated to deploy the target group snapshot.')
```
Comment (Steve-Mcl) [inline frontend/src/pages/application/DeviceGroup/devices.vue]: As per Nicks comment on the issue & discussion in slack, we need to include the snapshot details


> Update the existing 'confirm add' dialog to include details of the snapshot that will be deployed to the groups being added.
> This is the current dialog shown:
> 
> Image
> It should:
> 
> Change 'active pipeline snapshot' text to 'target group snapshot' to be consistent with other language
> Include the name of the snapshot in the dialog

I would also suggest we include the snapshot age (or date) to permit the user to make informed decision.

**Review by Steve-Mcl — COMMENTED** [review]
All good bar the snapshot details

File: frontend/src/pages/application/DeviceGroup/devices.vue (hunk 1 above)
Comment (Steve-Mcl) [reply frontend/src/pages/application/DeviceGroup/devices.vue]: Ben, given @cstns is working on the whole group management stuff in https://github.com/FlowFuse/flowfuse/pull/6157, I wonder if we should ship this as is and address the messaging as a separate follow up issue? (since applying a group is now possible from different locations in the app - a common Pr and approach would be warranted)?

Comment (hardillb) [reply frontend/src/pages/application/DeviceGroup/devices.vue]: @Steve-Mcl I've updated to include snapshot id and name (same as top right hand corner)

File: frontend/src/pages/application/DeviceGroup/devices.vue [hunk 2]
```diff
@@ -331,7 +331,7 @@ export default {
             const addedCount = devicesAdded.length
             const warning = []
             if (addedCount > 0) {
-                warning.push('1 or more devices will be added to this group. These device(s) will be updated to deploy the active pipeline snapshot.')
+                warning.push(`1 or more devices will be added to this group. These device(s) will be updated to deploy the target group snapshot (${this.deviceGroup.targetSnapshot.id}, ${this.deviceGroup.targetSnapshot.name}).`)
```
Comment (Steve-Mcl) [inline frontend/src/pages/application/DeviceGroup/devices.vue]: When there is no target, this will show undefined. 

Image

**Comment by Steve-Mcl** [comment]
Also noticed: Asking to clear when no target is set.

image

**Comment by Steve-Mcl** [comment]
Approved, waiting tests before merge. 
If this slips my mind, feel free to merge.

**Comment by hardillb** [comment]
@Steve-Mcl the postgres tests keeps timing out, will see if they run this time.

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl the postgres tests keeps timing out, will see if they run this time.

Ahha, possibly due to `it('All Devices removed get an update request and clears DeviceGroup.targetSnapshotId', ...` in test/unit/forge/ee/routes/api/applicationDeviceGroups_spec.js

Why its timing out and not failing is a different matter!

**Comment by hardillb** [comment]
@Steve-Mcl thanks, will look closer when done with the point release

**Comment by Steve-Mcl** [comment]
@hardillb I was in the test so just pushed an update.

**Comment by hardillb** [comment]
@Steve-Mcl looks good
