### PR TITLE
Render Blueprint descriptions as markdown

### LINKED ISSUE #6983: Blueprint description field: Markdown formatting not rendered but recommended in UI
When creating a blueprint in FlowFuse, the description field recommends using Markdown formatting. However, the description is never actually rendered as Markdown - it is displayed as plain text with all Markdown syntax visible.

This creates a poor user experience because:
- The visible Markdown syntax (e.g., `##`, `**`, `*`, `-`) makes the description less readable
- Users follow the UI recommendation and add Markdown, expecting it to improve formatting
- The result is actually worse readability than plain text would provide

### Current Behavior

The blueprint creation form suggests: "Use markdown for formatting"

Image

The description is stored with Markdown syntax but displayed as raw text, showing all formatting characters instead of rendering them.

Image

### Expected Behavior

Either:
1. **Render the Markdown**: Display the description with proper Markdown formatting (headings, bold, lists, etc.)
2. **Remove the recommendation**: Don't suggest Markdown if it won't be rendered, and update the UI text to indicate plain text only

### Steps to Reproduce

1. Navigate to blueprint creation in FlowFuse
2. Enter a description with Markdown formatting (e.g., headings with `##`, bold with `**`)
3. Save the blueprint
4. View the blueprint description
5. Observe that Markdown syntax is visible as raw text, not rendered

### Environment

- Forge Application: v2.19.0
- Location: Blueprint creation/editing interface

### Suggested Solution

If rendering Markdown is not feasible or desired, remove the recommendation from the UI and clarify that plain text should be used.

If Markdown rendering is intended, implement proper Markdown-to-HTML rendering where blueprint descriptions are displayed.

### PR DESCRIPTION
**Pull request by hardillb**
fixes #6983

## Description

Blueprint descriptions are supposed to be markdown

## Related Issue(s)

#6983 

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production
 - [ ] Link to Changelog Entry PR, or note why one is not needed.

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: frontend/src/components/blueprints/BlueprintTile.vue [hunk 1]
```diff
@@ -16,7 +16,9 @@
         </div>
         <div class="ff-blueprint-tile--info">
             <label>{{ blueprint.name }}</label>
-            <p :title="blueprint.description">{{ blueprint.description }}</p>
+            <p :title="blueprint.description">
```
Comment (cstns) [inline frontend/src/components/blueprints/BlueprintTile.vue]: the content prop on the ff-markdown-viewer component is required, we should gate the entire paragraph behind a v-if

Comment (cstns) [inline frontend/src/components/blueprints/BlueprintTile.vue]:
```suggestion
            <p v-if="blueprint.description" :title="blueprint.description">
```
