### PR TITLE
Ensure pipelines empty state has a feature unavailable message

### LINKED ISSUE #3218: Missing message from "Feature Unavailable" in pipeline when in CE mode
### Current Behavior

Empty state feature unavailable message missing

image

### Expected Behavior

empty state component Should have prop `featureUnavailableMessage`

### Steps To Reproduce

visit application pipelines on a CE installation

### Environment

- FlowForge version: 1.14.1

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #3218 

## Description

Adds text to missing feature banner

### Before
image

### After
image

## Related Issue(s)

 #3218

### CODE REVIEW

File: frontend/src/pages/application/Pipelines.vue [hunk 1]
```diff
@@ -50,7 +50,7 @@
             @stage-deleted="(stageIndex) => stageDeleted(pipeline, stageIndex)"
         />
     </div>
-    <EmptyState v-else :featureUnavailable="!featureEnabled">
+    <EmptyState v-else :featureUnavailable="!featureEnabled" :featureUnavailableMessage="'This feature is not available'">
```
Comment (Pezmc) [inline frontend/src/pages/application/Pipelines.vue:53]: I'd be tempted to move this to a default in `EmptyState`

Comment (Pezmc) [reply frontend/src/pages/application/Pipelines.vue:53]: https://github.com/FlowFuse/flowfuse/blob/12af24aee95be79c1702ba5a401e4eb02eeba598/frontend/src/components/banners/FeatureUnavailable.vue#L23-L26

Comment (Pezmc) [reply frontend/src/pages/application/Pipelines.vue:53]: It's being explicitly set to `null` (rather than `undefined`) in EmptyState, and thus the default is not applying.

File: frontend/src/pages/application/Pipelines.vue [hunk 2]
```diff
@@ -50,7 +50,7 @@
             @stage-deleted="(stageIndex) => stageDeleted(pipeline, stageIndex)"
         />
     </div>
-    <EmptyState v-else :featureUnavailable="!featureEnabled" :featureUnavailableMessage="'This feature is not available'">
+    <EmptyState :featureUnavailable="true">
```
Comment (Steve-Mcl) [inline frontend/src/pages/application/Pipelines.vue:53]: @Pezmc why have you sset this always `true`?

Comment (Pezmc) [reply frontend/src/pages/application/Pipelines.vue]: Because I pushed my tests while rushing to be done 🙈

**Review by knolleary — APPROVED** [review]
