### PR TITLE
Fix: N+1 query for StorageFlows for Instance State End Points

### LINKED ISSUE #2952: N+1 Query
Sentry Issue: [FLOWFUSE-BACKEND-M](https://flowfuse.sentry.io/issues/4546949659/?referrer=github_integration)
|  |  |
| ------------- | --------------- |
| **Offending Spans** | db - SELECT "id", "flow", "updatedAt" FROM "Sto...

### LINKED ISSUE #2954: N+1 Query for Application Status
Sentry Issue: [FLOWFUSE-BACKEND-K](https://flowfuse.sentry.io/issues/4545921029/?referrer=github_integration)
|  |  |
| ------------- | --------------- |
| **Offending Spans** | db - SELECT "id", "flow", "updatedAt" FROM "Sto...

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

The flowLastUpdatedAt value that's returned from status endpoints for instances is based on the instances StorageFlow.
Previously the `liveStatus` view loaded the StorageFlow, which meant it was happening for each instance we display, not a problem on the instance endpoint, but when loading all instance statuses for an application lead to a slow querytime.

This PR:
 - Updates the view to use `model.StorageFlow`, rather than loading it from the DB, if set
 - Associates StorageFlows with Instances (previously only one way)
 - Includes the StorageFlow when the instance is loaded, if the flag is set

Should reduce a 200ms+ query for some of our larger customers down to <25ms.

## Related Issue(s)

Fixes #2952
Fixes #2954 

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by hardillb — APPROVED** [review]

**Comment by hardillb** [comment]
Merge when tests pass

File: forge/db/models/Application.js [hunk 1]
```diff
@@ -70,7 +70,17 @@ module.exports = {
...
                                 }
                             ]
-                        })
+                        }
+
+                        if (includeInstanceStorageFlow) {
+                            // Used for instance status
+                            include.include.push({
+                                model: M.StorageFlow,
+                                attributes: ['id', 'flow', 'updatedAt']
```
Comment (knolleary) [inline forge/db/models/Application.js:79]: At first glance, I can't see anywhere we use `flow` from this - given that *could* be sizeable it would be waste of effort to retrieve if all we want is the `updatedAt` column

Comment (Pezmc) [reply forge/db/models/Application.js:79]: Agreed, `flow` shouldn't be there!

Comment (Pezmc) [reply forge/db/models/Application.js]: [4b93619](https://github.com/FlowFuse/flowfuse/pull/2955/commits/4b93619b91b2a80ad94a8c50d6225a4cffb7284a)
